server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/web_check_in?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: web-check-in
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 10
      max-active: 100
  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: always
      platform: mysql
  data:
    redis:
      host: 127.0.0.1
      port: 6378